### ISSUE TITLE
Support darwin-arm64

### ISSUE THREAD

**Issue by itsMaxC** [rsese/gh-actions-status#1]
This would be necessary for support on M1 Macs.

**Comment by rsese** [comment]
sorry I missed this!  releases are generated with https://github.com/cli/gh-extension-precompile and darwin-arm64 support has since been added in https://github.com/cli/gh-extension-precompile/releases/tag/v1.1.2.  Just pushed another release and looks like it worked:

* https://github.com/rsese/gh-actions-status/releases/tag/v1.1.0
* https://github.com/rsese/gh-actions-status/releases/download/v1.1.0/darwin-arm64

**Comment by itsMaxC** [comment]
Awesome!  I had forked the repo and used Go to build/release it with darwin-arm64 (which worked fine) but I will archive it now that I can use the original repo.
